ai:
  api_url: http://localhost:11434
  fallback_models:
  - gemma2:2b
  - llama3.2:3b
  model: gemma2:2b
  provider: ollama
monitoring:
  enabled: true
  interval: 30
replication:
  enabled: false
  servers: []
system:
  autonomy_level: 1
  max_instances: 5
  name: JARVIS
  version: 1.0.0
